
# Generate arrays for basic mathematical operations

In [2]:
import numpy as np

a = np.arange(1,6)
b = np.arange(6,11)

print("Add: ",a+b)
print("Sub: ",a-b)
print("Mul: ",a*b)
print("Div: ",a/b)

Add:  [ 7  9 11 13 15]
Sub:  [-5 -5 -5 -5 -5]
Mul:  [ 6 14 24 36 50]
Div:  [0.16666667 0.28571429 0.375      0.44444444 0.5       ]


# Create 3*3 matrix and perform operations

In [3]:

matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])
print("Original matrix: \n", matrix)

# tranpose
transpose = matrix.T
print("Transpose: \n", transpose)

another_matrix = np.array([[9,8,7],[6,5,4],[3,2,1]])
print("Addition: \n", matrix+another_matrix)
print("Multiplication: \n", matrix*another_matrix)

Original matrix: 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Transpose: 
 [[1 4 7]
 [2 5 8]
 [3 6 9]]
Addition: 
 [[10 10 10]
 [10 10 10]
 [10 10 10]]
Multiplication: 
 [[ 9 16 21]
 [24 25 24]
 [21 16  9]]


# Create 4*4 matrix calculate sum of its rows and columns

In [4]:
matrix = np.random.randint(0,10,size=(4,4))
print("Matrix: \n",matrix)
sum_rows = np.sum(matrix,axis=1)
print(sum_rows)
sum_columns = np.sum(matrix,axis=0)
print(sum_columns)

Matrix: 
 [[8 3 4 5]
 [3 1 3 4]
 [9 3 0 8]
 [8 8 7 1]]
[20 11 20 24]
[28 15 14 18]


# Write a program to normalize an array(scale values between 0 to 1)

In [5]:

arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
print("Array: \n",arr)

arr = arr.astype(float)

min = np.min(arr)
max = np.max(arr)

normalised = []

if min == max:
    normalised = np.zeros_like(arr)
else:
    normalised = (arr - min)/(max-min)
    
print("Normalised array: \n",normalised)

Array: 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Normalised array: 
 [[0.    0.125 0.25 ]
 [0.375 0.5   0.625]
 [0.75  0.875 1.   ]]


# Generate a random array and find the minimum and maximum values

In [6]:

arr = np.random.randint(0,9,size=(3,3))
print("Array: \n",arr)
print("Min:",np.min(arr))
print("Max:",np.max(arr))

Array: 
 [[5 0 1]
 [5 1 2]
 [3 1 4]]
Min: 0
Max: 5


# Broad Casting

In [16]:
matrix = np.array([[1,2,3], [4,5,6], [7,8,9]])
vector = np.array([1,0,-1])
result_add = matrix+vector
print("ADD: \n",result_add)
result_mul = matrix*vector
print("MUL: \n",result_mul)

ADD: 
 [[2 2 2]
 [5 5 5]
 [8 8 8]]
MUL: 
 [[ 1  0 -3]
 [ 4  0 -6]
 [ 7  0 -9]]


# Generate and filter a Random Dataset

In [18]:
import numpy as np

# generate random dataset
dataset = np.random.randint(1,51, size=(5,5))
print("original: \n", dataset)

# filter values > 5 and replace with 0
dataset[dataset > 25] = 0
print("Modified dataset: \n", dataset)

# calculate summary stats
print("Sum: ", np.sum(dataset))
print("mean: ",np.mean(dataset)) 
print("max: ",np.max(dataset))
print("min: ",np.min(dataset)) 
print("standard deviation: ",np.std(dataset))
print("sum along rows: ",np.sum(dataset,axis=1)) 
print("sum along columns: ",np.sum(dataset,axis=0))

original: 
 [[31  1 40 26 28]
 [12 10 14  3 17]
 [24 18 18 50 45]
 [ 8  3 30 36 39]
 [38 16 16 24 42]]
Modified dataset: 
 [[ 0  1  0  0  0]
 [12 10 14  3 17]
 [24 18 18  0  0]
 [ 8  3  0  0  0]
 [ 0 16 16 24  0]]
Sum:  184
mean:  7.36
max:  24
min:  0
standard deviation:  8.41370310861989
sum along rows:  [ 1 56 60 11 56]
sum along columns:  [44 48 48 27 17]


# Create a 3d random array and compute statistics along specific axis

In [ ]:
import numpy as np

arr_3d = np.random.randint(0,10,size=(3,3,3))
print("3d random array: \n", arr_3d) 

mean_axis0 = np.mean(arr_3d, axis=0)
std_axis0 = np.std(arr_3d, axis=0)
min_axis0 = np.min(arr_3d, axis=0)
max_axis0 = np.max(arr_3d, axis=0)

print("Mean along axis=0:\n", mean_axis0, "\n")
print("Standard Deviation along axis=0:\n", std_axis0, "\n")
print("Minimum along axis=0:\n", min_axis0, "\n")
print("Maximum along axis=0:\n", max_axis0, "\n")

3d random array: 
 [[[0 6 3]
  [2 3 1]
  [7 3 1]]

 [[7 8 1]
  [6 1 1]
  [2 6 6]]

 [[7 9 8]
  [6 8 6]
  [9 5 6]]]
Mean along axis=0:
 [[4.66666667 7.66666667 4.        ]
 [4.66666667 4.         2.66666667]
 [6.         4.66666667 4.33333333]] 

Standard Deviation along axis=0:
 [[3.29983165 1.24721913 2.94392029]
 [1.88561808 2.94392029 2.3570226 ]
 [2.94392029 1.24721913 2.3570226 ]] 

Minimum along axis=0:
 [[0 6 1]
 [2 1 1]
 [2 3 1]] 

Maximum along axis=0:
 [[7 9 8]
 [6 8 6]
 [9 6 6]] 



# write program to generate dataset of random float and the values between 0 and 1

In [30]:
import random 
# Function to generate dataset of random floats 
def generate_dataset(size): 
    dataset = [random.random() for _ in range(size)] 
    return dataset 

if __name__ == "__main__": 
    size = 10 # number of random floats you want 
    data = generate_dataset(size) 
    print("Random float dataset between 0 and 1:") 
    print(data)

Random float dataset between 0 and 1:
[0.7676584056493077, 0.9026778482726628, 0.23301934713888295, 0.0436537109399493, 0.006389544110096956, 0.32187810218628377, 0.8135520087579197, 0.15100905996027403, 0.29063970186142474, 0.1750147716221393]


# Implement conditional replacement to create a binary mask for values above a threshold

In [31]:
import numpy as np

# Function to create binary mask
def create_binary_mask(data, threshold):
    # Replace values: 1 if above threshold, else 0
    mask = np.where(data > threshold, 1, 0)
    return mask

# Example usage
if __name__ == "__main__":
    # Sample dataset of random floats between 0 and 1
    data = np.random.rand(10)  
    print("Original data:", data)

    threshold = 0.5
    mask = create_binary_mask(data, threshold)
    print(f"Binary mask (threshold = {threshold}):", mask)


Original data: [0.99042063 0.90993319 0.76894662 0.63731937 0.54911208 0.25982201
 0.97206829 0.64425878 0.4580933  0.5271187 ]
Binary mask (threshold = 0.5): [1 1 1 1 1 0 1 1 0 1]
