# Generate arrays for basic mathematical operations

In [7]:
import numpy as np

a = np.arange(1,6)
b = np.arange(6,11)

print("Add: ",a+b)
print("Sub: ",a-b)
print("Mul: ",a*b)
print("Div: ",a/b)

Add:  [ 7  9 11 13 15]
Sub:  [-5 -5 -5 -5 -5]
Mul:  [ 6 14 24 36 50]
Div:  [0.16666667 0.28571429 0.375      0.44444444 0.5       ]


# Create 3*3 matrix and perform operations

In [12]:
matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])
print("Original matrix: \n", matrix)

# tranpose
transpose = matrix.T
print("Transpose: \n", transpose)

another_matrix = np.array([[9,8,7],[6,5,4],[3,2,1]])
print("Addition: \n", matrix+another_matrix)
print("Multiplication: \n", matrix*another_matrix)

Original matrix: 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Transpose: 
 [[1 4 7]
 [2 5 8]
 [3 6 9]]
Addition: 
 [[10 10 10]
 [10 10 10]
 [10 10 10]]
Multiplication: 
 [[ 9 16 21]
 [24 25 24]
 [21 16  9]]


# Create 4*4 matrix calculate sum of its rows and columns

In [19]:
matrix = np.random.randint(0,10,size=(4,4))
print("Matrix: \n",matrix)
sum_rows = np.sum(matrix,axis=1)
print(sum_rows)
sum_columns = np.sum(matrix,axis=0)
print(sum_columns)


Matrix: 
 [[8 5 2 2]
 [1 1 8 0]
 [5 0 9 9]
 [1 4 0 6]]
[17 10 23 11]
[15 10 19 17]


# Write a program to normalize an array(scale values between 0 to 1)

In [20]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
print("Array: \n",arr)

arr = arr.astype(float)

min = np.min(arr)
max = np.max(arr)

normalised = []

if min == max:
    normalised = np.zeros_like(arr)
else:
    normalised = (arr - min)/(max-min)
    
print("Normalised array: \n",normalised)

Array: 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Normalised array: 
 [[0.    0.125 0.25 ]
 [0.375 0.5   0.625]
 [0.75  0.875 1.   ]]


# Generate a random array and find the minimum and maximum values

In [42]:
arr = np.random.randint(0,9,size=(3,3))
print("Array: \n",arr)
print("Min:",np.min(arr))
print("Max:",np.max(arr))

Array: 
 [[5 6 4]
 [4 3 3]
 [5 1 7]]
Min: 1
Max: 7
