In [1]:
import numpy as np

a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])

In [2]:
# Addition and subtraction
print('Addition: \n',a+b)
print('subtraction: \n',b-a)

Addition: 
 [[ 6  8]
 [10 12]]
subtraction: 
 [[4 4]
 [4 4]]


In [3]:
# scalar multiplication
c=2*a
print('scalar multiplication: \n',c)

scalar multiplication: 
 [[2 4]
 [6 8]]


In [4]:
# matrix multiplication:
result = np.dot(a,b)
print('matrix multiplication: \n',result)

matrix multiplication: 
 [[19 22]
 [43 50]]


In [5]:
# Identity matrix
i = np.eye(3)
print('identity matrix: \n',i)

identity matrix: 
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
# zero matrix
z = np.zeros((2,3))
print('zero matrix: \n',z)

zero matrix: 
 [[0. 0. 0.]
 [0. 0. 0.]]


In [7]:
# Diagonal matrix
d = np.diag([1,2,3])
print('diagonal matrix: \n',d)

diagonal matrix: 
 [[1 0 0]
 [0 2 0]
 [0 0 3]]
